### ISSUE TITLE
Mac Encoding Fix

### ISSUE THREAD

**Issue by seba90** [code-iai/ease-fall-school-day-3-exercises#1]
Warning: the environment variable LANG is not set!

We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.

Creating a virtualenv for this project...

Pipfile: /Users/asil/Desktop/ease-fall-school-day-3-exercises-master/Pipfile

Using /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 (2.7.13) to create virtualenv...

⠋Traceback (most recent call last):

  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/pew/__main__.py", line 8, in <module>

    import pew

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/pew/__init__.py", line 3, in <module>

    from . import pew

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/pew/pew.py", line 44, in <module>

    from pew._utils import (check_call, invoke, expandpath, own, env_bin_dir,

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/site-packages/pipenv/patched/pew/_utils.py", line 25, in <module>

    encoding = locale.getlocale()[1] or 'ascii'

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/locale.py", line 587, in getlocale

    return _parse_localename(localename)

  File "/usr/local/Cellar/pipenv/2018.7.1/libexec/lib/python3.7/locale.py", line 495, in _parse_localename

    raise ValueError('unknown locale: %s' % localename)

ValueError: unknown locale: UTF-8

**Comment by seba90** [comment]
Fix:

https://stackoverflow.com/questions/7165108/in-os-x-lion-lang-is-not-set-to-utf-8-how-to-fix-it
